using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Onion.CleanArchitecture.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddHangFire : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "JobId",
                table: "OrderTimers",
                type: "text",
                nullable: true);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "InboxState" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "MessageId" uuid NOT NULL,
                    "ConsumerId" uuid NOT NULL,
                    "LockId" uuid NOT NULL,
                    "RowVersion" bytea NULL,
                    "Received" timestamp with time zone NOT NULL,
                    "ReceiveCount" integer NOT NULL,
                    "ExpirationTime" timestamp with time zone NULL,
                    "Consumed" timestamp with time zone NULL,
                    "Delivered" timestamp with time zone NULL,
                    "LastSequenceNumber" bigint NULL,
                    CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
                    CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
                );
                CREATE INDEX IF NOT EXISTS "IX_InboxState_Delivered" ON "InboxState" ("Delivered");
                CREATE TABLE IF NOT EXISTS "OutboxState" (
                    "OutboxId" uuid NOT NULL,
                    "LockId" uuid NOT NULL,
                    "RowVersion" bytea NULL,
                    "Created" timestamp with time zone NOT NULL,
                    "Delivered" timestamp with time zone NULL,
                    "LastSequenceNumber" bigint NULL,
                    CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
                );
                CREATE INDEX IF NOT EXISTS "IX_OutboxState_Created" ON "OutboxState" ("Created");
                CREATE TABLE IF NOT EXISTS "OutboxMessage" (
                    "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "EnqueueTime" timestamp with time zone NULL,
                    "SentTime" timestamp with time zone NOT NULL,
                    "Headers" text NULL,
                    "Properties" text NULL,
                    "InboxMessageId" uuid NULL,
                    "InboxConsumerId" uuid NULL,
                    "OutboxId" uuid NULL,
                    "MessageId" uuid NOT NULL,
                    "ContentType" character varying(256) NOT NULL,
                    "MessageType" text NOT NULL,
                    "Body" text NOT NULL,
                    "ConversationId" uuid NULL,
                    "CorrelationId" uuid NULL,
                    "InitiatorId" uuid NULL,
                    "RequestId" uuid NULL,
                    "SourceAddress" character varying(256) NULL,
                    "DestinationAddress" character varying(256) NULL,
                    "ResponseAddress" character varying(256) NULL,
                    "FaultAddress" character varying(256) NULL,
                    "ExpirationTime" timestamp with time zone NULL,
                    CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber"),
                    CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId"
                        FOREIGN KEY ("InboxMessageId", "InboxConsumerId") REFERENCES "InboxState" ("MessageId", "ConsumerId"),
                    CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId"
                        FOREIGN KEY ("OutboxId") REFERENCES "OutboxState" ("OutboxId")
                );
                CREATE INDEX IF NOT EXISTS "IX_OutboxMessage_EnqueueTime" ON "OutboxMessage" ("EnqueueTime");
                CREATE INDEX IF NOT EXISTS "IX_OutboxMessage_ExpirationTime" ON "OutboxMessage" ("ExpirationTime");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber"
                    ON "OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutboxMessage_OutboxId_SequenceNumber"
                    ON "OutboxMessage" ("OutboxId", "SequenceNumber");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "OutboxMessage";""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "InboxState";""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "OutboxState";""");

            migrationBuilder.DropColumn(
                name: "JobId",
                table: "OrderTimers");
        }
    }
}
