version: '3.0'
services:
  postgres:
    image: postgres:16
    container_name: LearnSaga
    environment:
      POSTGRES_DB: LearnSaga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2375
    ports:
      - 5432:5432
    networks:
      - learn-saga
    volumes:
      - portgres_data:/var/lib/portgresql/data
  webapp:
    container_name: webapp
    image: onion.clean:v.0.1
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      SQLSERVER_CONNECTION_STRING: Host=postgres;Port=5432;Database=LearnSaga;Username=postgres;Password=2375;
    networks:
      - learn-saga
networks:
  learn-saga:
    driver: bridge
    name: learn-saga
    external: true
volumes:
  portgres_data:
